---
- name: Install prerequisites
  become: yes
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present

- name: Check for Gravity Sync executable
  ansible.builtin.stat:
    path: "{{ executable }}"
  register: gs

- name: Install Gravity Sync
  block:
    - name: Retrieve installer script
      ansible.builtin.get_url:
        url: "{{ installer_url }}"
        dest: /tmp/gravity.sh
        mode: 0775

    - name: Run install script
      shell: /tmp/gravity.sh
      environment:
        GS_INSTALL: "{{ pihole_role }}"

    - name: Setup executable symlink
      become: yes
      ansible.builtin.file:
        src: "{{ executable }}"
        dest: "{{ executable_symlink }}"
        state: link

    - name: Cleanup
      ansible.builtin.file:
        path: /tmp/gravity.sh
        state: absent
  when: gs.stat.isreg is not defined and pihole_role == "secondary"

- name: Update Gravity Sync
  command: "{{ executable }} update"
  when: gs.stat.isreg is defined and gs.stat.isreg
...